/*let myStr = "Firstline\nSecondline\nThirdLine"
console.log(myStr);*/

//Checking the last letter of a word without knowing the lenght.

/*let firstName = "Endie"
let testing = firstName[firstName.length - 3]
console.log(testing);*/

/*Testing a code that could solve matrix
let matrixValues = [[1,2,3], [3,2,1]]
let matrixSolution =matrixValues[0][0] * matrixValues[1][0];
console.log(matrixSolution);*/



