// for (let i = 1; i <= 20; i++) {
//   console.log(i);
// }

// for (let i = 10; i >= 1; i--) {
//     console.log(i);
//   }


//Function Declaration//
// function multiply(firstnumber, secondnumber, thirdnumber){
//   return firstnumber * secondnumber * thirdnumber;

// }
// console.log(multiply(4, 2, 2));
// console.log(multiply(5, 5, 5));

//Function Expression//
// function subtract(currentYear, yearOfBirth){
//   return currentYear - yearOfBirth;
// }
// console.log(subtract(2023, 2005));
const callBirthYear =() =>{
  
}
