let fruits = ["guava", "pawpaw", "Watermelon"];
console.log(fruits)

//To add elements to the beginning of an array
fruits.unshift("Cucumber")
console.log(fruits)


//To add elements to the end of an array
fruits.push("StarApple")
console.log(fruits)


//To remove the last element of an array
fruits.pop()
console.log(fruits)

//To remove the first element of an array
fruits.shift()
console.log(fruits)


// fruits.unshift("Orange")
// console.log(fruits)
// fruits.pop()
// console.log(fruits)
// fruits.push("Star Apple")
// console.log(fruits)
// fruits.shift()
// console.log(fruits)